/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package training.book.sb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Training service. Represents a row in the &quot;TB_Training&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link training.book.sb.model.impl.TrainingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link training.book.sb.model.impl.TrainingImpl}.
 * </p>
 *
 * @author Vishal Kumar Nalla
 * @see Training
 * @see training.book.sb.model.impl.TrainingImpl
 * @see training.book.sb.model.impl.TrainingModelImpl
 * @generated
 */
@ProviderType
public interface TrainingModel extends BaseModel<Training>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a training model instance should use the {@link Training} interface instead.
	 */

	/**
	 * Returns the primary key of this training.
	 *
	 * @return the primary key of this training
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this training.
	 *
	 * @param primaryKey the primary key of this training
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this training.
	 *
	 * @return the uuid of this training
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this training.
	 *
	 * @param uuid the uuid of this training
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the training ID of this training.
	 *
	 * @return the training ID of this training
	 */
	public long getTrainingId();

	/**
	 * Sets the training ID of this training.
	 *
	 * @param trainingId the training ID of this training
	 */
	public void setTrainingId(long trainingId);

	/**
	 * Returns the group ID of this training.
	 *
	 * @return the group ID of this training
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this training.
	 *
	 * @param groupId the group ID of this training
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this training.
	 *
	 * @return the company ID of this training
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this training.
	 *
	 * @param companyId the company ID of this training
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this training.
	 *
	 * @return the user ID of this training
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this training.
	 *
	 * @param userId the user ID of this training
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this training.
	 *
	 * @return the user uuid of this training
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this training.
	 *
	 * @param userUuid the user uuid of this training
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this training.
	 *
	 * @return the user name of this training
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this training.
	 *
	 * @param userName the user name of this training
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this training.
	 *
	 * @return the create date of this training
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this training.
	 *
	 * @param createDate the create date of this training
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this training.
	 *
	 * @return the modified date of this training
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this training.
	 *
	 * @param modifiedDate the modified date of this training
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the training name of this training.
	 *
	 * @return the training name of this training
	 */
	@AutoEscape
	public String getTrainingName();

	/**
	 * Sets the training name of this training.
	 *
	 * @param trainingName the training name of this training
	 */
	public void setTrainingName(String trainingName);

	/**
	 * Returns the training description of this training.
	 *
	 * @return the training description of this training
	 */
	@AutoEscape
	public String getTrainingDescription();

	/**
	 * Sets the training description of this training.
	 *
	 * @param trainingDescription the training description of this training
	 */
	public void setTrainingDescription(String trainingDescription);

	/**
	 * Returns the tutor ID of this training.
	 *
	 * @return the tutor ID of this training
	 */
	public long getTutorId();

	/**
	 * Sets the tutor ID of this training.
	 *
	 * @param tutorId the tutor ID of this training
	 */
	public void setTutorId(long tutorId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(training.book.sb.model.Training training);

	@Override
	public int hashCode();

	@Override
	public CacheModel<training.book.sb.model.Training> toCacheModel();

	@Override
	public training.book.sb.model.Training toEscapedModel();

	@Override
	public training.book.sb.model.Training toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}