/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package training.book.sb.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Tutor service. Represents a row in the &quot;TB_Tutor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link training.book.sb.model.impl.TutorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link training.book.sb.model.impl.TutorImpl}.
 * </p>
 *
 * @author Vishal Kumar Nalla
 * @see Tutor
 * @see training.book.sb.model.impl.TutorImpl
 * @see training.book.sb.model.impl.TutorModelImpl
 * @generated
 */
@ProviderType
public interface TutorModel extends BaseModel<Tutor>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tutor model instance should use the {@link Tutor} interface instead.
	 */

	/**
	 * Returns the primary key of this tutor.
	 *
	 * @return the primary key of this tutor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tutor.
	 *
	 * @param primaryKey the primary key of this tutor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this tutor.
	 *
	 * @return the uuid of this tutor
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this tutor.
	 *
	 * @param uuid the uuid of this tutor
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the tutor ID of this tutor.
	 *
	 * @return the tutor ID of this tutor
	 */
	public long getTutorId();

	/**
	 * Sets the tutor ID of this tutor.
	 *
	 * @param tutorId the tutor ID of this tutor
	 */
	public void setTutorId(long tutorId);

	/**
	 * Returns the group ID of this tutor.
	 *
	 * @return the group ID of this tutor
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tutor.
	 *
	 * @param groupId the group ID of this tutor
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tutor.
	 *
	 * @return the company ID of this tutor
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tutor.
	 *
	 * @param companyId the company ID of this tutor
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tutor.
	 *
	 * @return the user ID of this tutor
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tutor.
	 *
	 * @param userId the user ID of this tutor
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tutor.
	 *
	 * @return the user uuid of this tutor
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this tutor.
	 *
	 * @param userUuid the user uuid of this tutor
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tutor.
	 *
	 * @return the user name of this tutor
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tutor.
	 *
	 * @param userName the user name of this tutor
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tutor.
	 *
	 * @return the create date of this tutor
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tutor.
	 *
	 * @param createDate the create date of this tutor
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tutor.
	 *
	 * @return the modified date of this tutor
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tutor.
	 *
	 * @param modifiedDate the modified date of this tutor
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the tutor name of this tutor.
	 *
	 * @return the tutor name of this tutor
	 */
	@AutoEscape
	public String getTutorName();

	/**
	 * Sets the tutor name of this tutor.
	 *
	 * @param tutorName the tutor name of this tutor
	 */
	public void setTutorName(String tutorName);

	/**
	 * Returns the tutor email of this tutor.
	 *
	 * @return the tutor email of this tutor
	 */
	@AutoEscape
	public String getTutorEmail();

	/**
	 * Sets the tutor email of this tutor.
	 *
	 * @param tutorEmail the tutor email of this tutor
	 */
	public void setTutorEmail(String tutorEmail);

	/**
	 * Returns the training ID of this tutor.
	 *
	 * @return the training ID of this tutor
	 */
	public long getTrainingId();

	/**
	 * Sets the training ID of this tutor.
	 *
	 * @param trainingId the training ID of this tutor
	 */
	public void setTrainingId(long trainingId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(training.book.sb.model.Tutor tutor);

	@Override
	public int hashCode();

	@Override
	public CacheModel<training.book.sb.model.Tutor> toCacheModel();

	@Override
	public training.book.sb.model.Tutor toEscapedModel();

	@Override
	public training.book.sb.model.Tutor toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}