/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package training.book.sb.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import training.book.sb.model.Tutor;
import training.book.sb.model.TutorModel;
import training.book.sb.model.TutorSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Tutor service. Represents a row in the &quot;TB_Tutor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TutorModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TutorImpl}.
 * </p>
 *
 * @author Vishal Kumar Nalla
 * @see TutorImpl
 * @see Tutor
 * @see TutorModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TutorModelImpl extends BaseModelImpl<Tutor> implements TutorModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tutor model instance should use the {@link Tutor} interface instead.
	 */
	public static final String TABLE_NAME = "TB_Tutor";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "tutorId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "tutorName", Types.VARCHAR },
			{ "tutorEmail", Types.VARCHAR },
			{ "trainingId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tutorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("tutorName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tutorEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trainingId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table TB_Tutor (uuid_ VARCHAR(75) null,tutorId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,tutorName VARCHAR(75) null,tutorEmail VARCHAR(75) null,trainingId LONG)";
	public static final String TABLE_SQL_DROP = "drop table TB_Tutor";
	public static final String ORDER_BY_JPQL = " ORDER BY tutor.tutorId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TB_Tutor.tutorId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(training.book.sb.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.training.book.sb.model.Tutor"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(training.book.sb.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.training.book.sb.model.Tutor"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(training.book.sb.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.training.book.sb.model.Tutor"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long TRAININGID_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;
	public static final long TUTORID_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Tutor toModel(TutorSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Tutor model = new TutorImpl();

		model.setUuid(soapModel.getUuid());
		model.setTutorId(soapModel.getTutorId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTutorName(soapModel.getTutorName());
		model.setTutorEmail(soapModel.getTutorEmail());
		model.setTrainingId(soapModel.getTrainingId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Tutor> toModels(TutorSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Tutor> models = new ArrayList<Tutor>(soapModels.length);

		for (TutorSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(training.book.sb.service.util.ServiceProps.get(
				"lock.expiration.time.training.book.sb.model.Tutor"));

	public TutorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tutorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTutorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tutorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Tutor.class;
	}

	@Override
	public String getModelClassName() {
		return Tutor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("tutorId", getTutorId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("tutorName", getTutorName());
		attributes.put("tutorEmail", getTutorEmail());
		attributes.put("trainingId", getTrainingId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long tutorId = (Long)attributes.get("tutorId");

		if (tutorId != null) {
			setTutorId(tutorId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String tutorName = (String)attributes.get("tutorName");

		if (tutorName != null) {
			setTutorName(tutorName);
		}

		String tutorEmail = (String)attributes.get("tutorEmail");

		if (tutorEmail != null) {
			setTutorEmail(tutorEmail);
		}

		Long trainingId = (Long)attributes.get("trainingId");

		if (trainingId != null) {
			setTrainingId(trainingId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTutorId() {
		return _tutorId;
	}

	@Override
	public void setTutorId(long tutorId) {
		_tutorId = tutorId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTutorName() {
		if (_tutorName == null) {
			return StringPool.BLANK;
		}
		else {
			return _tutorName;
		}
	}

	@Override
	public void setTutorName(String tutorName) {
		_tutorName = tutorName;
	}

	@JSON
	@Override
	public String getTutorEmail() {
		if (_tutorEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _tutorEmail;
		}
	}

	@Override
	public void setTutorEmail(String tutorEmail) {
		_tutorEmail = tutorEmail;
	}

	@JSON
	@Override
	public long getTrainingId() {
		return _trainingId;
	}

	@Override
	public void setTrainingId(long trainingId) {
		_columnBitmask |= TRAININGID_COLUMN_BITMASK;

		if (!_setOriginalTrainingId) {
			_setOriginalTrainingId = true;

			_originalTrainingId = _trainingId;
		}

		_trainingId = trainingId;
	}

	public long getOriginalTrainingId() {
		return _originalTrainingId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Tutor.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Tutor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Tutor toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Tutor)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TutorImpl tutorImpl = new TutorImpl();

		tutorImpl.setUuid(getUuid());
		tutorImpl.setTutorId(getTutorId());
		tutorImpl.setGroupId(getGroupId());
		tutorImpl.setCompanyId(getCompanyId());
		tutorImpl.setUserId(getUserId());
		tutorImpl.setUserName(getUserName());
		tutorImpl.setCreateDate(getCreateDate());
		tutorImpl.setModifiedDate(getModifiedDate());
		tutorImpl.setTutorName(getTutorName());
		tutorImpl.setTutorEmail(getTutorEmail());
		tutorImpl.setTrainingId(getTrainingId());

		tutorImpl.resetOriginalValues();

		return tutorImpl;
	}

	@Override
	public int compareTo(Tutor tutor) {
		long primaryKey = tutor.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Tutor)) {
			return false;
		}

		Tutor tutor = (Tutor)obj;

		long primaryKey = tutor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TutorModelImpl tutorModelImpl = this;

		tutorModelImpl._originalUuid = tutorModelImpl._uuid;

		tutorModelImpl._originalGroupId = tutorModelImpl._groupId;

		tutorModelImpl._setOriginalGroupId = false;

		tutorModelImpl._originalCompanyId = tutorModelImpl._companyId;

		tutorModelImpl._setOriginalCompanyId = false;

		tutorModelImpl._setModifiedDate = false;

		tutorModelImpl._originalTrainingId = tutorModelImpl._trainingId;

		tutorModelImpl._setOriginalTrainingId = false;

		tutorModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Tutor> toCacheModel() {
		TutorCacheModel tutorCacheModel = new TutorCacheModel();

		tutorCacheModel.uuid = getUuid();

		String uuid = tutorCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			tutorCacheModel.uuid = null;
		}

		tutorCacheModel.tutorId = getTutorId();

		tutorCacheModel.groupId = getGroupId();

		tutorCacheModel.companyId = getCompanyId();

		tutorCacheModel.userId = getUserId();

		tutorCacheModel.userName = getUserName();

		String userName = tutorCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			tutorCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			tutorCacheModel.createDate = createDate.getTime();
		}
		else {
			tutorCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			tutorCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			tutorCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		tutorCacheModel.tutorName = getTutorName();

		String tutorName = tutorCacheModel.tutorName;

		if ((tutorName != null) && (tutorName.length() == 0)) {
			tutorCacheModel.tutorName = null;
		}

		tutorCacheModel.tutorEmail = getTutorEmail();

		String tutorEmail = tutorCacheModel.tutorEmail;

		if ((tutorEmail != null) && (tutorEmail.length() == 0)) {
			tutorCacheModel.tutorEmail = null;
		}

		tutorCacheModel.trainingId = getTrainingId();

		return tutorCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", tutorId=");
		sb.append(getTutorId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", tutorName=");
		sb.append(getTutorName());
		sb.append(", tutorEmail=");
		sb.append(getTutorEmail());
		sb.append(", trainingId=");
		sb.append(getTrainingId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("training.book.sb.model.Tutor");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tutorId</column-name><column-value><![CDATA[");
		sb.append(getTutorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tutorName</column-name><column-value><![CDATA[");
		sb.append(getTutorName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tutorEmail</column-name><column-value><![CDATA[");
		sb.append(getTutorEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trainingId</column-name><column-value><![CDATA[");
		sb.append(getTrainingId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Tutor.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Tutor.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _tutorId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _tutorName;
	private String _tutorEmail;
	private long _trainingId;
	private long _originalTrainingId;
	private boolean _setOriginalTrainingId;
	private long _columnBitmask;
	private Tutor _escapedModel;
}